version: '3.8' 

services: 
  backend: 
    build: .   
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload"] 
    volumes: 
      - .:/code 
    ports:  
      - "80:80"